//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GittBilSmsCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GittBilSmsCore.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Detaylarını Girin.
        /// </summary>
        public static string _Enter_Company_Details {
            get {
                return ResourceManager.GetString(" Enter Company Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Firma.
        /// </summary>
        public static string Add_Company {
            get {
                return ResourceManager.GetString("Add Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API&apos;si.
        /// </summary>
        public static string API {
            get {
                return ResourceManager.GetString("API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Yönetimi.
        /// </summary>
        public static string API_Management {
            get {
                return ResourceManager.GetString("API Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her yazarın ortalama aylık satışı.
        /// </summary>
        public static string Average_monthly_sale_for_every_author {
            get {
                return ResourceManager.GetString("Average monthly sale for every author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal edildi.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek talebi gönderemesin.
        /// </summary>
        public static string Cannot_send_support_request {
            get {
                return ResourceManager.GetString("Cannot send support request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api seç.
        /// </summary>
        public static string Choose_API {
            get {
                return ResourceManager.GetString("Choose API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmalar.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Bilgileri.
        /// </summary>
        public static string Company_Information {
            get {
                return ResourceManager.GetString("Company Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Adı.
        /// </summary>
        public static string Company_Name {
            get {
                return ResourceManager.GetString("Company Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Kullancıları.
        /// </summary>
        public static string Company_Users {
            get {
                return ResourceManager.GetString("Company Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamamlanmış.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturan.
        /// </summary>
        public static string Created_By {
            get {
                return ResourceManager.GetString("Created By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturulma Tarihi.
        /// </summary>
        public static string Creation_Date {
            get {
                return ResourceManager.GetString("Creation Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Yüklemeleri.
        /// </summary>
        public static string Credit_Topups {
            get {
                return ResourceManager.GetString("Credit Topups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para birimi.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol Paneli.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderim Tarihi.
        /// </summary>
        public static string Date_of_Sending {
            get {
                return ResourceManager.GetString("Date of Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderileceği tarihi ( ileri tarihli sipariş ).
        /// </summary>
        public static string Dateofshipment {
            get {
                return ResourceManager.GetString("Dateofshipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayiler.
        /// </summary>
        public static string Dealers {
            get {
                return ResourceManager.GetString("Dealers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslim edilmiş.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rehber.
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimum dosya boyutu 25 MB. (excel, csv, txt) .
        /// </summary>
        public static string Filemessage1 {
            get {
                return ResourceManager.GetString("Filemessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel ve csv dosyalarınızda telefon numaraları &apos;A&apos; kolonunda bulunmak zorundadır..
        /// </summary>
        public static string Filemessage2 {
            get {
                return ResourceManager.GetString("Filemessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        public static string Firm {
            get {
                return ResourceManager.GetString("Firm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geçen aydan itibaren.
        /// </summary>
        public static string from_last_month {
            get {
                return ResourceManager.GetString("from last month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yüksek (1.000.000 üzeri sms birim fiyat).
        /// </summary>
        public static string High__Unit_price_for_SMS_over_1_000_000_ {
            get {
                return ResourceManager.GetString("High (Unit price for SMS over 1,000,000)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Numaralar.
        /// </summary>
        public static string Invalid_Numbers {
            get {
                return ResourceManager.GetString("Invalid Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yüklendi.
        /// </summary>
        public static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturumu kapat.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düşük (1-500.000 arası sms birim fiyat).
        /// </summary>
        public static string Low__1_500_000_SMS_unit_price_ {
            get {
                return ResourceManager.GetString("Low (1-500,000 SMS unit price)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetim.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orta (500.000-1.000.000 arası sms birim fiyat).
        /// </summary>
        public static string Medium__500_000_1_000_000_SMS_unit_price_ {
            get {
                return ResourceManager.GetString("Medium (500,000-1,000,000 SMS unit price)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özel karakterler 2 karakter sayılmaktadır..
        /// </summary>
        public static string MessageText {
            get {
                return ResourceManager.GetString("MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylık Gelir.
        /// </summary>
        public static string Monthly_Revenue {
            get {
                return ResourceManager.GetString("Monthly Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Yeni Sipariş.
        /// </summary>
        public static string New_Order {
            get {
                return ResourceManager.GetString("New Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numaralar.
        /// </summary>
        public static string Numbers {
            get {
                return ResourceManager.GetString("Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklemede.
        /// </summary>
        public static string On_Hold {
            get {
                return ResourceManager.GetString("On Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasyon.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişler.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre bilgisi en az 8 karakter olmalı, en az 1 büyük harf, 1 küçük harf, 1 rakam ve 1 özel karakter barındırmalıdır..
        /// </summary>
        public static string Password_Information {
            get {
                return ResourceManager.GetString("Password Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçmiş mesajlar.
        /// </summary>
        public static string Past_messages {
            get {
                return ResourceManager.GetString("Past messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Askıda olması.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyatlandırma.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlendi.
        /// </summary>
        public static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Siparişler.
        /// </summary>
        public static string Recent_Orders {
            get {
                return ResourceManager.GetString("Recent Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri ödemek.
        /// </summary>
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İade edilebilir.
        /// </summary>
        public static string Refundable {
            get {
                return ResourceManager.GetString("Refundable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlar.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıfırla.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dönüş Tarihi.
        /// </summary>
        public static string Return_Date {
            get {
                return ResourceManager.GetString("Return Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İade edildi.
        /// </summary>
        public static string Returned {
            get {
                return ResourceManager.GetString("Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roller.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Sms Gönder.
        /// </summary>
        public static string Sendsms {
            get {
                return ResourceManager.GetString("Sendsms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderim Türü.
        /// </summary>
        public static string Submission_Type {
            get {
                return ResourceManager.GetString("Submission Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göndermek.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek Talepleri.
        /// </summary>
        public static string Support_Requests {
            get {
                return ResourceManager.GetString("Support Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugün Gönderilen SMS.
        /// </summary>
        public static string Today_sms_sent {
            get {
                return ResourceManager.GetString("Today sms sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Tutar.
        /// </summary>
        public static string Total_Amount {
            get {
                return ResourceManager.GetString("Total Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenilir gönderici.
        /// </summary>
        public static string Trusted_sender {
            get {
                return ResourceManager.GetString("Trusted sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarısız.
        /// </summary>
        public static string Unsuccessful {
            get {
                return ResourceManager.GetString("Unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Bilgileri.
        /// </summary>
        public static string User_Information {
            get {
                return ResourceManager.GetString("User Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı.
        /// </summary>
        public static string User_name {
            get {
                return ResourceManager.GetString("User name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcometurkish.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekrar hoşgeldiniz.
        /// </summary>
        public static string Welcome_Back {
            get {
                return ResourceManager.GetString("Welcome Back", resourceCulture);
            }
        }
    }
}
